import { config as loadEnv } from "dotenv";

loadEnv({ path: ".env.local", override: true });
loadEnv();

import { PrismaNeon } from "@prisma/adapter-neon";
import { JobGroup, PrismaClient, TaskCategory, TaskPriority, TaskType } from "@prisma/client";

const connectionString =
  process.env.DATABASE_URL ??
  "postgresql://placeholder:placeholder@127.0.0.1:5432/chocobo?sslmode=require";
const adapter = new PrismaNeon({ connectionString });
const prisma = new PrismaClient({ adapter });

const tasks = [
  {
    slug: "duty-roulette-leveling",
    name: "Duty Roulette: Leveling",
    description: "Grande pico de XP para subir o Warrior e ajudar a manter filas rapidas como tank.",
    type: TaskType.DAILY,
    category: TaskCategory.ROULETTE,
    minLevel: 16,
    xpReward: 850000,
    goldReward: 5200,
    tomestones: 20,
    seals: 0,
    unlocked: true,
    unlockHint: null,
    infoUrl: "#",
    priority: TaskPriority.HIGH,
    requiredJobGroup: null,
    adventurerInNeedBonus: true,
  },
  {
    slug: "duty-roulette-trials",
    name: "Duty Roulette: Trials",
    description: "Boa XP e tomestones, ja disponivel no seu progresso de patch 2.x.",
    type: TaskType.DAILY,
    category: TaskCategory.ROULETTE,
    minLevel: 50,
    xpReward: 320000,
    goldReward: 3800,
    tomestones: 20,
    seals: 0,
    unlocked: true,
    unlockHint: null,
    infoUrl: "#",
    priority: TaskPriority.MEDIUM,
    requiredJobGroup: null,
    adventurerInNeedBonus: true,
  },
  {
    slug: "duty-roulette-main-scenario",
    name: "Duty Roulette: Main Scenario",
    description: "Otimo para XP, mas exige ter concluido as MSQs que liberam Castrum/Praetorium.",
    type: TaskType.DAILY,
    category: TaskCategory.ROULETTE,
    minLevel: 50,
    xpReward: 460000,
    goldReward: 4200,
    tomestones: 30,
    seals: 0,
    unlocked: true,
    unlockHint: "Requer completar as MSQs finais de A Realm Reborn.",
    infoUrl: "#",
    priority: TaskPriority.MEDIUM,
    requiredJobGroup: null,
    adventurerInNeedBonus: true,
  },
  {
    slug: "duty-roulette-guildhests",
    name: "Duty Roulette: Guildhests",
    description: "Rotina rapida e leve para bonus diario extra.",
    type: TaskType.DAILY,
    category: TaskCategory.ROULETTE,
    minLevel: 10,
    xpReward: 120000,
    goldReward: 1800,
    tomestones: 0,
    seals: 0,
    unlocked: true,
    unlockHint: null,
    infoUrl: "#",
    priority: TaskPriority.LOW,
    requiredJobGroup: null,
    adventurerInNeedBonus: false,
  },
  {
    slug: "amaljaa-dailies",
    name: "Beast Tribe quests - Amalj'aa",
    description: "Tres quests rapidas por dia para reputacao e XP em classe de combate.",
    type: TaskType.DAILY,
    category: TaskCategory.BEAST_TRIBE,
    minLevel: 41,
    xpReward: 180000,
    goldReward: 1500,
    tomestones: 0,
    seals: 0,
    unlocked: true,
    unlockHint: null,
    infoUrl: "#",
    priority: TaskPriority.MEDIUM,
    requiredJobGroup: null,
    adventurerInNeedBonus: false,
  },
  {
    slug: "sylph-dailies",
    name: "Beast Tribe quests - Sylphs",
    description: "Mais tres quests de reputacao para variar enquanto voce fecha ARR.",
    type: TaskType.DAILY,
    category: TaskCategory.BEAST_TRIBE,
    minLevel: 41,
    xpReward: 180000,
    goldReward: 1500,
    tomestones: 0,
    seals: 0,
    unlocked: true,
    unlockHint: null,
    infoUrl: "#",
    priority: TaskPriority.MEDIUM,
    requiredJobGroup: null,
    adventurerInNeedBonus: false,
  },
  {
    slug: "kobold-dailies",
    name: "Beast Tribe quests - Kobolds",
    description: "Reputacao ARR com XP estavel para jobs de combate.",
    type: TaskType.DAILY,
    category: TaskCategory.BEAST_TRIBE,
    minLevel: 41,
    xpReward: 180000,
    goldReward: 1500,
    tomestones: 0,
    seals: 0,
    unlocked: true,
    unlockHint: null,
    infoUrl: "#",
    priority: TaskPriority.MEDIUM,
    requiredJobGroup: null,
    adventurerInNeedBonus: false,
  },
  {
    slug: "sahagin-dailies",
    name: "Beast Tribe quests - Sahagin",
    description: "Boa opcao para intercalar reputacao e XP sem entrar em duty.",
    type: TaskType.DAILY,
    category: TaskCategory.BEAST_TRIBE,
    minLevel: 41,
    xpReward: 180000,
    goldReward: 1500,
    tomestones: 0,
    seals: 0,
    unlocked: true,
    unlockHint: null,
    infoUrl: "#",
    priority: TaskPriority.MEDIUM,
    requiredJobGroup: null,
    adventurerInNeedBonus: false,
  },
  {
    slug: "ixal-dailies",
    name: "Beast Tribe quests - Ixal",
    description: "Daily exclusiva para crafter/gatherer, util quando voce quiser avancar DoH/DoL.",
    type: TaskType.DAILY,
    category: TaskCategory.CRAFTING,
    minLevel: 45,
    xpReward: 140000,
    goldReward: 1000,
    tomestones: 0,
    seals: 0,
    unlocked: true,
    unlockHint: "Requer um crafter ou gatherer no nivel adequado.",
    infoUrl: "#",
    priority: TaskPriority.LOW,
    requiredJobGroup: JobGroup.CRAFTER_GATHERER,
    adventurerInNeedBonus: false,
  },
  {
    slug: "grand-company-expert-delivery",
    name: "Grand Company: Expert Delivery",
    description: "Turn-in de gear antigo para Grand Company seals e upgrades da sua GC.",
    type: TaskType.DAILY,
    category: TaskCategory.GRAND_COMPANY,
    minLevel: 20,
    xpReward: 0,
    goldReward: 0,
    tomestones: 0,
    seals: 3000,
    unlocked: true,
    unlockHint: "Disponivel apos avancar a Grand Company e liberar Expert Delivery.",
    infoUrl: "#",
    priority: TaskPriority.MEDIUM,
    requiredJobGroup: null,
    adventurerInNeedBonus: false,
  },
  {
    slug: "wondrous-tails",
    name: "Wondrous Tails",
    description: "Weekly de alto valor em Idyllshire. Bom objetivo de medio prazo, mas voce ainda nao desbloqueou.",
    type: TaskType.WEEKLY,
    category: TaskCategory.OTHER,
    minLevel: 60,
    xpReward: 0,
    goldReward: 0,
    tomestones: 0,
    seals: 0,
    unlocked: false,
    unlockHint: "Desbloqueia no nivel 60 em Idyllshire, ja em Heavensward.",
    infoUrl: "#",
    priority: TaskPriority.HIGH,
    requiredJobGroup: null,
    adventurerInNeedBonus: false,
  },
  {
    slug: "arr-hunt-marks",
    name: "Hunt Marks (ARR)",
    description: "Weekly das hunts do ARR para seals e um pouco de gil extra.",
    type: TaskType.WEEKLY,
    category: TaskCategory.HUNT,
    minLevel: 50,
    xpReward: 0,
    goldReward: 3000,
    tomestones: 0,
    seals: 120,
    unlocked: true,
    unlockHint: null,
    infoUrl: "#",
    priority: TaskPriority.MEDIUM,
    requiredJobGroup: null,
    adventurerInNeedBonus: false,
  },
  {
    slug: "challenge-log-overview",
    name: "Challenge Log entries",
    description: "Lembrete macro das metas semanais que resetam toda terca-feira as 08:00 UTC.",
    type: TaskType.WEEKLY,
    category: TaskCategory.CHALLENGE_LOG,
    minLevel: 15,
    xpReward: 280000,
    goldReward: 3000,
    tomestones: 0,
    seals: 0,
    unlocked: true,
    unlockHint: "Requer liberar o Challenge Log em Limsa Lominsa.",
    infoUrl: "#",
    priority: TaskPriority.HIGH,
    requiredJobGroup: null,
    adventurerInNeedBonus: false,
  },
  {
    slug: "challenge-log-party-duties",
    name: "Challenge Log: vencer 5 duties em party",
    description: "E semanal, mas vale acompanhar ao longo da semana como uma meta recorrente.",
    type: TaskType.WEEKLY,
    category: TaskCategory.CHALLENGE_LOG,
    minLevel: 15,
    xpReward: 150000,
    goldReward: 1000,
    tomestones: 0,
    seals: 0,
    unlocked: true,
    unlockHint: "Requer o Challenge Log desbloqueado.",
    infoUrl: "#",
    priority: TaskPriority.MEDIUM,
    requiredJobGroup: null,
    adventurerInNeedBonus: false,
  },
  {
    slug: "custom-deliveries",
    name: "Custom Deliveries",
    description: "Placeholder para seu loop futuro de crafter/gatherer quando chegar em Heavensward avancado.",
    type: TaskType.WEEKLY,
    category: TaskCategory.CRAFTING,
    minLevel: 60,
    xpReward: 0,
    goldReward: 0,
    tomestones: 0,
    seals: 0,
    unlocked: false,
    unlockHint: "Desbloqueia mais tarde em Heavensward e pede foco em DoH/DoL.",
    infoUrl: "#",
    priority: TaskPriority.LOW,
    requiredJobGroup: JobGroup.CRAFTER_GATHERER,
    adventurerInNeedBonus: false,
  },
] as const;

async function ensureSettings() {
  return prisma.userSettings.upsert({
    where: { id: "singleton" },
    update: {
      currentLevel: 58,
      currentJob: "Warrior",
      timezone: "America/Sao_Paulo",
    },
    create: {
      id: "singleton",
      currentLevel: 58,
      currentJob: "Warrior",
      timezone: "America/Sao_Paulo",
    },
  });
}

async function main() {
  await ensureSettings();

  for (const task of tasks) {
    await prisma.task.upsert({
      where: { slug: task.slug },
      update: task,
      create: task,
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
